# Generated by Django 3.1.6 on 2021-02-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=50, verbose_name='Диагональ')),
                ('resolution', models.CharField(max_length=50, verbose_name='Разрешение экрана')),
                ('processor', models.CharField(max_length=100, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('accum', models.CharField(max_length=50, verbose_name='Аккумулятор')),
                ('sd', models.BooleanField(default=True)),
                ('memory_volume', models.CharField(max_length=100, verbose_name='Объём встроенной памяти')),
                ('main_camera', models.CharField(max_length=100, verbose_name='Основная камера')),
                ('front_camera', models.CharField(max_length=100, verbose_name='фронтальная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=50, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=100, verbose_name='Тип дисплея')),
                ('processor', models.CharField(max_length=100, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('video', models.CharField(max_length=100, verbose_name='Видеокарта')),
                ('time_without_charge', models.CharField(max_length=50, verbose_name='Время без подзарядки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
